export const categoryPills = ["All", "AI", "FinTech", "HealthTech", "EdTech", "SaaS", "Climate"]

export const sortOptions = ["Trending", "Newest", "Most Funded", "Alphabetical"]

export const industryFilters = ["Enterprise AI", "Clean Energy", "Biotech"]

export const stageOptions = ["Any Stage", "Pre-Seed", "Seed", "Series A", "Series B+"]

export const defaultFilters = {
    industries: [],
    stage: "Any Stage",
    fundingGoal: 50,
    location: "",
}

export const promoCard = {
    id: "ai-visionary-program",
    title: "AI Visionary Program",
    description: "Join the exclusive incubator for generative AI startups. Apply by Nov 15th.",
    ctaLabel: "Apply Now",
}

export const mockStartups = [
    {
        id: "veridian",
        featured: true,
        name: "Veridian",
        logo: "https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?w=150&q=80",
        category: "Climate",
        industries: ["Clean Energy"],
        stage: "Series A",
        description: "Decentralizing vertical farming with AI-driven modular units for urban environments. Solving food security at scale.",
        image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=900&q=80",
        tags: ["AI Optimized", "Sustainability"],
        badge: "Startup of the Day",
        location: "Rotterdam, NL",
        fundingGoalAmount: 12,
        raisedPercent: null,
        createdAt: "2024-10-02",
        trendingScore: 96,
    },
    {
        id: "kryptos-security",
        name: "Kryptos Security",
        category: "AI",
        industries: ["Enterprise AI"],
        stage: "Seed",
        description: "Post-quantum encryption for distributed enterprise networks.",
        founder: { name: "Mateus Chen", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80" },
        fundingGoalLabel: "$3.4M",
        fundingGoalAmount: 3.4,
        raisedPercent: 67,
        location: "Berlin, DE",
        createdAt: "2024-11-18",
        trendingScore: 78,
    },
    {
        id: "biosense-labs",
        name: "BioSense Labs",
        category: "HealthTech",
        industries: ["Biotech"],
        stage: "Series A",
        description: "Real-time non-invasive glucose monitoring using optical sensors.",
        image: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=600&q=80",
        location: "Austin, TX",
        fundingGoalAmount: 4,
        raisedPercent: null,
        createdAt: "2024-09-14",
        trendingScore: 61,
    },
    {
        id: "lumina-ed",
        name: "Lumina Ed",
        category: "EdTech",
        industries: [],
        stage: "Pre-Seed",
        description: "Personalized adaptive learning paths for K-12 students using neuro-linguistic programming models.",
        image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80",
        founders: [
            { avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&q=80" },
            { avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80" },
        ],
        membersLabel: "12 Members",
        fundingTargetLabel: "$1.2M Target",
        fundingGoalAmount: 1.2,
        raisedPercent: null,
        location: "Toronto, CA",
        createdAt: "2024-12-01",
        trendingScore: 54,
    },
    {
        id: "orbit-logix",
        name: "Orbit Logix",
        category: "SaaS",
        industries: ["Enterprise AI"],
        stage: "Series A",
        description: "Low-earth orbit satellite maintenance automation.",
        badge: "Trending",
        activity: "Active 2h ago",
        location: "Toulouse, FR",
        fundingGoalAmount: 8,
        raisedPercent: null,
        createdAt: "2025-01-05",
        trendingScore: 91,
    },
    {
        id: "urbangrid",
        name: "UrbanGrid",
        category: "Climate",
        industries: ["Clean Energy"],
        stage: "Series B+",
        description: "Optimizing municipal energy distribution through real-time traffic data ingestion.",
        image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
        badge: "High Momentum",
        founder: { name: "Sarah J. Mittal", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80" },
        location: "Singapore, SG",
        fundingGoalAmount: 6,
        raisedPercent: null,
        createdAt: "2024-08-22",
        trendingScore: 72,
    },
    {
        id: "paystream",
        name: "PayStream",
        category: "FinTech",
        industries: ["Enterprise AI"],
        stage: "Seed",
        description: "Instant cross-border settlement rails for SMB marketplaces.",
        founder: { name: "Priya Nandakumar", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80" },
        fundingGoalLabel: "$5M",
        fundingGoalAmount: 5,
        raisedPercent: 34,
        location: "New York, NY",
        createdAt: "2025-01-20",
        trendingScore: 68,
    },
    {
        id: "dataforge",
        name: "DataForge",
        category: "SaaS",
        industries: ["Enterprise AI"],
        stage: "Series A",
        description: "Unified data pipelines for mid-market analytics teams.",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
        location: "Seattle, WA",
        fundingGoalAmount: 9,
        raisedPercent: null,
        createdAt: "2024-07-30",
        trendingScore: 58,
    },
]